---
- name: Install and configure Loadbalancer, Apps and Database Cluster
  hosts: all
  become: true

  vars:
    db_packages:
    - wget
    - gnupg2
    - lsb-release
    - curl
    - xz-utils
    - python3-pip
    - percona-xtradb-cluster
    lb_packages:
    - nginx
    app_packages:
    - nginx
    - php-fpm
    - php-mysql
    - unzip
    - percona-xtradb-cluster-client
    - proxysql2
    - python3-pip
    wp_db_name: "wordpress"
    wp_db_user: "wordpress"
    wp_db_pass: "wordpresspassword"
    wp_db_host: "127.0.0.1"
    wp_db_port: "6033"


  tasks:
  - name: Disable auto updates on Ubuntu
    ansible.builtin.copy:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      content: |
        APT::Periodic::Update-Package-Lists "0";
        APT::Periodic::Unattended-Upgrade "0";
    when: ansible_distribution == 'Ubuntu'

  - name: Install and configure Database
    include_tasks: "db.yaml"
    when: inventory_hostname in groups["db"]

  - name: Install and configure Apps
    include_tasks: "app.yaml"
    when: inventory_hostname in groups["app"]

  - name: Install and configure Loadbalancer
    include_tasks: "lb.yaml"
    when: inventory_hostname in groups["lb"]

  handlers:
  - name: restart php-fpm
    ansible.builtin.systemd:
      name: "php8.1-fpm.service"
      state: restarted
  
  - name: nginx reload
    ansible.builtin.systemd:
      name: "nginx"
      state: reloaded

  - name: restart mariadb-server
    ansible.builtin.systemd:
      name: "mariadb.service"
      state: restarted
